apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrtesting123
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: acrtesting123
  template:
    metadata:
      labels:
        app: acrtesting123
    spec:
      containers:
        - name: acrtesting123
          image: mcr.microsoft.com/mcr/hello-world  
          ports:
            - containerPort: 80
