apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app: sample-app  # Match the label selector with your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
