name: Azure Kubernetes Service CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Pull sample app image from Docker Hub
      run: docker pull mcr.microsoft.com/mcr/hello-world 

    - name: Login to Azure Container Registry
      run: az acr login --name acrtesting123.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

    - name: Tag Docker image for ACR
      run: docker tag mcr.microsoft.com/mcr/hello-world acrtesting123.azurecr.io/mcr.microsoft.com/mcr/hello-world 

    - name: Push Docker image to Azure Container Registry
      run: docker push acrtesting123.azurecr.io/mcr.microsoft.com/mcr/hello-world

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Set Kubernetes Context for AKS Cluster
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: akstesting
        resource-group: aks-demo
        cluster-context: akstesting
        
    - name: List Files in Repository
      run: ls -R
    - name: Set KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        
    - name: Debug KUBECONFIG
      run: cat $KUBECONFIG
    - name: Set Kubernetes Context
      run: kubectl config use-context akstesting

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v1
      with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          manifests: |
            ./kubernetes/deployment.yaml
            ./kubernetes/service.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

