name: CI/CD for Azure Kubernetes Service

on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acrtesting123.azurecr.io 
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Pull Docker image from Docker Hub
      run: docker pull mcr.microsoft.com/hello-world
      
    - name: Tag Docker image for ACR
      run: docker tag mcr.microsoft.com/hello-world acrtesting123.azurecr.io/hello-world:v1

    - name: Push Docker image to ACR
      run: docker push acrtesting123.azurecr.io/hello-world:v1

    - name: Deploy to AKS
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yaml
        kubectl config use-context <your-aks-context-name>
        kubectl apply -f Deployment.yml
        kubectl apply -f service.yml
        kubectl apply -f ingress.yml
