name: Azure Kubernetes Service CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up KUBECONFIG
      run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Pull sample app image from Docker Hub
      run: docker pull mcr.microsoft.com/mcr/hello-world 

    - name: Login to Azure Container Registry
      run: az acr login --name acrtesting123.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

    - name: Tag Docker image for ACR
      run: docker tag mcr.microsoft.com/mcr/hello-world acrtesting123.azurecr.io/mcr.microsoft.com/mcr/hello-world 

    - name: Push Docker image to Azure Container Registry
      run: docker push acrtesting123.azurecr.io/mcr.microsoft.com/mcr/hello-world

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Set Kubernetes Context for AKS Cluster
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: akstesting
        resource-group: aks-demo
        cluster-context: akstesting
        
    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group aks-demo --name akstesting --context myContext


    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v1
      with:
          manifests: |
            ./kubernetes/deployment.yaml
            ./kubernetes/service.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

